### PR TITLE
Admin event delete updates

### PR DESCRIPTION
**Pull request by ruchali1**
- Updated Visibility of Buttons
- Once an item is removed the button is "GONE"
- Added Edit Mode Label to hide edit button in edit mode 
- Added Cascade deletes
- When a facility is deleted all events with that facility are deleted (based on organizerID) - and the facility itself are deleted
- Logic: Each Organizer has an OrganizerID linked to all their events, so if there facility is removed all their events (queried on organizerID) are deleted) : this logic should be checked as part of this review

### CODE REVIEW

**Comment by aabrady6** [comment]
During testing, found bug:
1. Delete facility on admin view - successfully deletes the events associated with the user. Events are removed from db.
2. Create a new facility
3. Deleted events reappear in the DB with different event-ID and same information as before.

**Comment by aabrady6** [comment]
moving to draft status

**Comment by ruchali1** [comment]
Tested with new main (duplicate event fix) @aabrady6

**Comment by aabrady6** [comment]
commented out a toast as it was crashing. pls re-test and should be good to merge after that.

**Comment by aabrady6** [comment]
looks good. merging

**Pull request merged**
